[pytest]

;addopts = --headed --browser chromium --browser firefox --browser webkit
;addopts = --headed --browser chromium
;addopts = --headed --device="iPhone 13"

addopts =
    --headed
;    --browser-chanel chrome
;    --tracing on